### ISSUE TITLE
Migrate to maven central

### ISSUE THREAD

**Issue by jeremyrempel** [Giphy/giphy-android-sdk#118]
jcenter will be sunset on May 1, 2020 [announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by ALexanderLonsky** [comment]
hey @jeremyrempel, thank you for the update! We are working on this.

**Comment by ALexanderLonsky** [comment]
@jeremyrempel we have migrated to [Maven Central](https://repo1.maven.org/maven2/com/giphy/sdk/ui/).
