### ISSUE TITLE
How to fetch Gif Url from SDK

### ISSUE THREAD

**Issue by shivchauhans** [Giphy/giphy-android-sdk#123]
All i am getting from media is:
Url: https://giphy.com/gifs/IntoAction-lanterns-stop-asian-hate-end-violence-against-asians-cNwLEqnkZ99oL4oBKa

bitlyUrl: https://gph.is/g/ZP87wml

bitlyGifUrl: https://gph.is/g/ZP87wml

embedUrl: https://giphy.com/embed/cNwLEqnkZ99oL4oBKa

These all are not .gif links which can be rendered in App.
How to get proper .gif link of selected GIF from DialogFragment, can someone help please?

**Comment by ALexanderLonsky** [comment]
hey @shivchauhans,
`Media` model has `images` collection that contains all images types(renditions). Each rendition represents `Image` where you can take either `gifUrl`  or `webPUrl`.
