### ISSUE TITLE
NullPointerException: SimpleDraweeView was not initialized! / Binary XML file line #31: Binary XML file line #31: Error inflating class com.giphy.sdk.ui.views.GPHMediaView

### ISSUE THREAD

**Issue by annaharri89** [Giphy/giphy-android-sdk#125]
I'm trying to update our giphy dependency to version 2.0.9, but the app crashes when it tries to inflate a com.giphy.sdk.ui.views.GPHMediaView. I'm doing the ` GiphyCore.configure` call before I inflate the activities layout in the onCreate

In sentry it says something about `NullPointerException: SimpleDraweeView was not initialized!`

**Comment by ALexanderLonsky** [comment]
hey @annaharri89,
this is weird. 
could you please try to configure the GIPHY SDK right before opening GiphyDialogFragment like: 
`val dialog = GiphyDialogFragment.newInstance(settings.copy(selectedContentType = contentType), YOUR_ANDROID_SDK_KEY)`

What Giphy SDK version does work for you? We have changed nothing related to SDK configuration in v 2.0.9.

Does our example app work for you?

**Comment by annaharri89** [comment]
@ALexanderLonsky  I need to configure the giphy sdk before I show the giphy dialog fragment. The app is a chat app. And people can send the gifs to each other. We have incoming/outgoing message viewHolders that contain the GPHMediaView for the sent gifs. And so we have to configure in onCreate of the activity.

Right now 2.0.1 is working well for us

**Comment by ALexanderLonsky** [comment]
@annaharri89 please, if possible, could you provide a sample app to reproduce the issue on my end?
Could you please check what exact version after `2.0.1` starts crashing for you so I can see what has been modified?

**Comment by annaharri89** [comment]
@ALexanderLonsky Yes I can do both of those things, but it might be a few days before I can get you what you asked for, heads up.

**Comment by ALexanderLonsky** [comment]
@annaharri89 thank you so much!

**Comment by annaharri89** [comment]
@ALexanderLonsky I don't know what changed, but now version 2.0.9 isn't crashing our app anymore

**Comment by ALexanderLonsky** [comment]
@annaharri89 thank you for the update, let's wait some time, and then you can close the issue if everything works as expected.
