### ISSUE TITLE
No static method getAdSession(Lcom/giphy/sdk/core/models/Media;)

### ISSUE THREAD

**Issue by annaharri89** [Giphy/giphy-android-sdk#126]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/16767360/114637309-fedf3300-9c96-11eb-8e97-50bcacad5300.png">

 

I'm getting the above crash and don't understand what it means. Can anyone provide any insight into it?

**Comment by ALexanderLonsky** [comment]
@annaharri89 what SDK version do you use, 2.0.9?
I see neither `getAdSession` nor `GPHAdSession` when searching our codebase.
Honestly, I don't understand it now too but will take a look.

Do you happen to have any example app to reproduce the crash?

**Comment by annaharri89** [comment]
this crash actually happened on version 1.0.0 of the giphy sdk. I'm working on a branch where I've updated to 2.0.9, but I haven't released that to the public yet. I haven't been able to reproduce the crash more than once, so I can't make you an example app.

**Comment by ALexanderLonsky** [comment]
@annaharri89 it seems we used to have the ad tracking in that old version but don't have it anymore. I think an update to the latest one should resolve your issue.

**Comment by annaharri89** [comment]
kk, thanks!
