### ISSUE TITLE
Few Crashes in Giphy SDK

### ISSUE THREAD

**Issue by faltutechy** [Giphy/giphy-android-sdk#128]
Hello Giphy Team
We have recntly integrated Giphy SDK in Our Project.
We are seeing 2,3 errors in our Firebase which are originating in Giphy SDK.
Attaching the errors with details here:
<img width="1129" alt="Screenshot 2021-04-27 at 11 01 36 AM" src="https://user-images.githubusercontent.com/69748785/116178516-48745700-a748-11eb-8478-1f59663f8d10.png">
<img width="1145" alt="Screenshot 2021-04-27 at 11 01 58 AM" src="https://user-images.githubusercontent.com/69748785/116178528-4ca07480-a748-11eb-90b2-31c2b5fe30ac.png">

**Comment by ALexanderLonsky** [comment]
hey @ChauhanRepo, thank you for flagging this.

How do you present `GiphyDialogFragment`?

**Comment by ALexanderLonsky** [comment]
duplicated: #133
