### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by hqinfosystem** [Giphy/giphy-android-sdk#129]
Hello GIPHY team,

I have integrated GIPHY SDK into my application and I'm checking from the last few days that GIPHY has some network error when I open it says "Oh No! Something Went Wrong." Retry

I have checked that my internet is working perfectly and all other application functionalities are working fine.
I have also a GIPHY production API key.

Thanks

**Comment by ALexanderLonsky** [comment]
hey @hqinfosystem
Thank you for flagging this, our team will check that.
Are you still experiencing the issue or not?

**Comment by hqinfosystem** [comment]
@ALexanderLonsky Thank you for your quick response I have sent an email. and yes I still experience the same issue.

**Comment by ALexanderLonsky** [comment]
@hqinfosystem thank you!
In the meanwhile, could you please try out our [demo example](https://s3.amazonaws.com/sdk.mobile.giphy.com/android/giphy-ui-sdk-example.apk)?

Is the issue happening only on opening the dialog? Does the "Retry" button work?
