### ISSUE TITLE
Theme color not changing for Giphy dialog fragment

### ISSUE THREAD

**Issue by iamajijul** [Giphy/giphy-android-sdk#132]
I'm trying to change the theme color by mentioning the required parameter on color xml, but it's not getting effect on dialog fragment for giphy. I'm trying on git hub sample for giphy . I'm trying to change the selection icon tint color.

**Comment by ALexanderLonsky** [comment]
@iamajijul you should override these two in values/colors.xml:
<color name="gph_active_image_color_light">#FF121212</color>
<color name="gph_active_image_color_dark">#FF00FF99</color>
