### ISSUE TITLE
How to share contents in the giphy grid view?

### ISSUE THREAD

**Issue by yash292005** [Giphy/giphy-android-sdk#134]
In the SDK they use on gif selection listener but if i wan to share the gif out of the app or download it ; how to do that?

note: the way shown in the tutorial dosent work

this is my code: 
package com.example.memeit

import android.app.Dialog
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.util.Log.d
import android.view.*
import android.widget.Toast
import androidx.appcompat.widget.SearchView
import androidx.core.content.ContextCompat
import androidx.fragment.app.DialogFragment
import androidx.fragment.app.Fragment
import com.giphy.sdk.core.models.Media
import com.giphy.sdk.core.models.enums.MediaType
import com.giphy.sdk.ui.GPHContentType
import com.giphy.sdk.ui.Giphy
import com.giphy.sdk.ui.pagination.GPHContent
import com.giphy.sdk.ui.universallist.SmartItemType
import com.giphy.sdk.ui.views.GPHGridCallback
import com.giphy.sdk.ui.views.GiphyDialogFragment
import com.giphy.sdk.ui.views.GiphyGridView
import com.giphy.sdk.ui.views.GiphyGridView.Companion.VERTICAL
import kotlinx.android.synthetic.main.fragment_pintrest_.*
import timber.log.Timber

class Pintrest_Fragment : Fragment() {
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
       val view = inflater.inflate(R.layout.fragment_pintrest_, container, false)
        setHasOptionsMenu(true)
        return view

    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setHasOptionsMenu(true)
        this.context?.let { Giphy.configure(it,"47kzPjMbjORmE51J07WxzhkEQTvkQTMl" ) }
        setTrendingQuery()
        val gridView = context?.let { GiphyGridView(it) }
        gridView?.callback = object : GPHGridCallback{
            override fun contentDidUpdate(resultCount: Int) {
                Timber.d("contentDidUpdate $resultCount")
            }

            override fun didSelectMedia(media: Media) {
                Toast.makeText(
                    context,
                    "media selected: ${media.id}",
                    Toast.LENGTH_SHORT
                ).show()
            }

        }

    }
    private fun setTrendingQuery(){
        val gridView = context?.let { GiphyGridView(it) }
        gridView?.direction = VERTICAL
        gridView?.spanCount = 2
        gridView?.cellPadding = 10
        gridView?.content = GPHContent.trendingGifs
        GridContainer?.removeAllViews()
        GridContainer?.addView(gridView)
    }
    private fun searchGifs(SearchInput:String){
        val gridView = context?.let { GiphyGridView(it) }
        gridView?.direction = VERTICAL
        gridView?.spanCount = 2
        gridView?.cellPadding = 10
        gridView?.content = GPHContent.searchQuery(SearchInput, MediaType.gif)
        GridContainer?.removeAllViews()
        GridContainer?.addView(gridView)
    }

    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        inflater.inflate(R.menu.search_menu, menu)
        val menuItem = menu.findItem(R.id.search_bar)
        val searchView = menuItem.actionView as SearchView
        searchView.setOnQueryTextListener(object : SearchView.OnQueryTextListener{
            override fun onQueryTextSubmit(query: String?): Boolean {
                if (query != null) {
                    searchGifs(query)
                    Toast.makeText(context, "Searching for $query", Toast.LENGTH_SHORT).show()
                }else{
                    setTrendingQuery()
                }
                return true
            }

            override fun onQueryTextChange(newText: String?): Boolean {
               return false
            }

        })
        super.onCreateOptionsMenu(menu, inflater)
    }
}

the toast  " Toast.makeText(
                    context,
                    "media selected: ${media.id}",
                    Toast.LENGTH_SHORT
                ).show()"
is not showing on the screen
please help

**Comment by ALexanderLonsky** [comment]
hey @yash292005,
please use our [GridView](https://github.com/Giphy/giphy-android-sdk/blob/main/app/src/main/java/com/giphy/sdk/uidemo/GridViewDemoActivity.kt) as a reference.
I just checked it works as expected:
<img width="392" alt="Screenshot 2021-06-17 at 13 30 20" src="https://user-images.githubusercontent.com/4112/122380103-32c52600-cf70-11eb-8286-f88a728d8282.png">

**Comment by yash292005** [comment]
please specify :
  val GridView = context?.let { GiphyGridView(it) }
        GridView?.callback = object : GPHGridCallback{
            override fun contentDidUpdate(resultCount: Int) {
                Timber.d("contentDidUpdate $resultCount")
            }

            override fun didSelectMedia(media: Media) {
                Toast.makeText(context, "your tapped $media.id", Toast.LENGTH_SHORT).show()
            }

        }

do you mean this?????

(BTW STILL DOSEN'T WORK )

**Comment by yash292005** [comment]
i'm unable to access the call back feature in my grid view reference

**Comment by ALexanderLonsky** [comment]
@yash292005 in your implementation you have 2 different instances of `GiphyGridView`.
The first one you create in `setTrendingQuery` by doing this: `context?.let { GiphyGridView(it) }`
And then, in `onViewCreated` you instantiate another one instead of using the previously created.

To fix the issue on your end, you'll need to do the following:

```
private fun setTrendingQuery(): GiphyGridView? {
        val gridView = context?.let { GiphyGridView(it) }
        ...
        return gridView
    }
```

```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
     ....
     val gridView = setTrendingQuery()
     gridView?.callback = object : GPHGridCallback {
     ....
}
```

**Comment by yash292005** [comment]
Thanks, I'll check it out.

**Comment by yash292005** [comment]
Thanks brother once again you saved my code it works just fine
