### ISSUE TITLE
'No GIFs Found' text appears in Black color when user searches for GIFs in Dark theme.

### ISSUE THREAD

**Issue by sinhasonu** [Giphy/giphy-android-sdk#135]
While searching for GIFs in dark theme, "No GIFs Found" appear in black color, Can anyone please help me that, How can I #override the color of " No GIFs Found" 
![InkedScreenshot_1623918807_LI](https://user-images.githubusercontent.com/32041390/122362575-dd8c1300-cf75-11eb-9491-564ce5b8dc2c.jpg)

**Comment by ALexanderLonsky** [comment]
@sinhasonu thank you for flagging this.
Please try this version: [2.1.1](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.1)

**Comment by sinhasonu** [comment]
Thanks @ALexanderLonsky  it worked :)
