### ISSUE TITLE
I Applied For a Production Sdk But It Got Rejected

### ISSUE THREAD

**Issue by yash292005** [Giphy/giphy-android-sdk#137]
I'm Ready to upgrade my app for production, but the application got rejected. What Should i do now ?
Also How to give attribute of  powered by giphy logo on Your App, Any Specific Places(Splash screens, Main Activities etc.)

**Comment by ALexanderLonsky** [comment]
hey @yash292005,
I'll check in regard to attribution. `GPHMediaView` has a branding logo. 
As for the rejection, is it related to Giphy SDK? What rejection message did you get?
