### ISSUE TITLE
Cant find .updateContent while using GridView

### ISSUE THREAD

**Issue by vikripermana21** [Giphy/giphy-android-sdk#141]
I cant find this .updateContent , i want to use giphy as GridView

![image](https://user-images.githubusercontent.com/68591896/126966668-194a6ca5-f2ff-4078-99a1-4290116e856d.png)

**Comment by ALexanderLonsky** [comment]
hey @vikripermana21, thank you for flagging this, I'll update the documentation.
It must be `content` property:
`gifsGridView?.content = gifsContent`
[Here](https://github.com/Giphy/giphy-android-sdk/blob/main/app/src/main/java/com/giphy/sdk/uidemo/GridViewDemoActivity.kt) is an example.
