### ISSUE TITLE
Could not get resource (Forbidden)

### ISSUE THREAD

**Issue by yravid** [Giphy/giphy-android-sdk#149]
Hi, 
Is there a problem with the https://giphy.bintray.com? 
I am trying to build my application and getting multiple HTTP 403 Forbidden from those resources:
```
'https://giphy.bintray.com/giphy-sdk/com/vonage/infrastructure-debug/2.5.583/infrastructure-debug-2.5.583.pom'
'https://giphy.bintray.com/giphy-sdk/com/leocardz/link-preview/2.0.0/link-preview-2.0.0.pom'.
'https://giphy.bintray.com/giphy-sdk/androidx/room/room-migration/maven-metadata.xml'
and more...
```
full error:
```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://giphy.bintray.com/giphy-sdk/com/smartlook/recording/app/1.7.0-native-experimental-rendering/app-1.7.0-native-experimental-rendering.pom'.
```

**Comment by ALexanderLonsky** [comment]
hey @yravid,
Jcenter is shutting down soon, as of version [2.1.1](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.1), Giphy SDK has been fully migrated off of Jcenter by pointing the dependencies to [MavenCentral](https://search.maven.org/artifact/com.giphy.sdk/ui).
Please follow [the Installation](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#installation) guide.

**Comment by yravid** [comment]
> hey @yravid,
> Jcenter is shutting down soon, as of version [2.1.1](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.1), Giphy SDK has been fully migrated off of Jcenter by pointing the dependencies to [MavenCentral](https://search.maven.org/artifact/com.giphy.sdk/ui).
> Please follow [the Installation](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#installation) guide.

Thanks @ALexanderLonsky, removed bintray from the build script and all seem to work again.
