### ISSUE TITLE
no content provider

### ISSUE THREAD

**Issue by khchoudhary8** [Giphy/giphy-android-sdk#155]
I am trying to upload the gif from giphy sdk to firebase but it seems that the content resolver is unable to get mime type from the Uri.parse(url of the gif); Hence i get an erroor of no content provider and app crashes. here is a snippet of my code. please help.

final GiphyDialogFragment dialog = GiphyDialogFragment.Companion.newInstance(settings);
                        dialog.setGifSelectionListener(new GiphyDialogFragment.GifSelectionListener() {
                            @Override
                            public void onGifSelected(@NonNull Media media, @Nullable String s, @NonNull GPHContentType gphContentType) {
                                final Image image = media
                                        .getImages()
                                        .getFixedWidth();
                                String url = null;
                                url = image.getGifUrl().trim();
                                Log.d("GIF",url);

                                ContentResolver resolver = getApplicationContext().getContentResolver();
                                MimeTypeMap mimeTypeMap = MimeTypeMap.getSingleton();
                                String a = resolver.getType(Uri.parse(url));
                                Toast.makeText(ChatDetailActivity.this, "hello "+a, Toast.LENGTH_SHORT).show();// prints hello null
                                Toast.makeText(ChatDetailActivity.this, "uri"+Uri.parse(url), Toast.LENGTH_SHORT).show();// prints the uri properly

                                String gif = mimeTypeMap.getExtensionFromMimeType(a);

                                StorageReference ref = FirebaseStorage.getInstance().getReference("GIF").child(System.currentTimeMillis()
                                        +"."+gif);
                                ref.putFile(Uri.parse(url)).addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
                                    @Override
                                    public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {

**Comment by ALexanderLonsky** [comment]
@khchoudhary8 
I think you need to download a gif and then use its local Uri.

**Comment by khchoudhary8** [comment]
@ALexanderLonsky  sir wont that cause delay and issues, like i am integrating this into a chatting app, it would have been better if the gif was not stored on the user's phone , would have directly sent to the other end user in the chat immediately through firebase.
Also then i need to think of an algo to save each gif with different name and then extract its uri ...Any workaround??
Btw thanks for your prompt reply..

**Comment by ALexanderLonsky** [comment]
@khchoudhary8 
It looks like Firebase Storage SDK does not work with remote files:
https://firebase.google.com/docs/storage/android/upload-files

As a workaround, you can try to get a file from the Fresco cache:

```
val url = media.images.fixedWidth!!.gifUrl
val imageRequest: ImageRequest? = ImageRequest.fromUri(url)
val cacheKey: CacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest, null)
val resource = ImagePipelineFactory.getInstance().mainFileCache.getResource(cacheKey)
val fileUri = Uri.fromFile((resource as FileBinaryResource).file)
```

This is uri of the cached file, I think `getExtensionFromMimeType` won't work, so you can provide it manually:
`+".gif"`

By default, `GiphyDialogFragment` uses `fixedWidth` rendition and `WEBP` image format.

So if you want the cached solution to work for you, you need to use `GIF` image format for `GiphyDialogFragment`:

`GiphyDialogFragment.newInstance(settings.copy(imageFormat = ImageFormat.GIF))`

**I wouldn't rely on the cache as it may be changed in the future.**

**Comment by khchoudhary8** [comment]
THANKS i didnt use fresco , i did save the gif in one of the folders in internal storage and uploaded it to firebase. it worked fine till yesterday but since today i am getting this weirdd error(Opening a new case). please help me..
