### ISSUE TITLE
Lightweight version?

### ISSUE THREAD

**Issue by EzequielAdrianM** [Giphy/giphy-android-sdk#157]
Any way to make this API more lightweight? Because once compiled, it adds about 5mb extra to the Android App Bundle package which (for my specific case) it is an increase of +72% in weight, very likely will lead to higher than usual uninstalls.

**Comment by ALexanderLonsky** [comment]
hey @EzequielAdrianM,
5mb is about right for what we include: Fresco, Exoplayer + other dependencies and resources.

**Comment by EzequielAdrianM** [comment]
Finally made a custom horizontal recyclerview for loading the trending/search GIFs into ImageView with the help of Glide, and a custom JsonRequest to the Tenor API. Unlike giphy, their api provides the .GIF direct URL without any wrapping webpage so Glide can download it directly. In just 300kb extra when compiling the App bundle. So far makes sense for my requirements. Peace out!

**Comment by ALexanderLonsky** [comment]
@EzequielAdrianM thank you and sorry to hear about this.
Giphy SDK-UI brings the full GIPHY experience directly to your app.
If a custom solution works for you, you can also use [Giphy API](https://developers.giphy.com/docs/api#quick-start-guide).
Moreover, we still provide [SDK-Core](https://search.maven.org/artifact/com.giphy.sdk/core/3.1.6/aar) but do not support it anymore.
It'll also add 300kb extra.
And you can still use Glide(it'll add 300kb more)
[Here](https://github.com/Giphy/giphy-android-sdk/blob/main/app/src/main/java/com/giphy/sdk/uidemo/DemoActivityJava.java) you can find an example.
