### ISSUE TITLE
Any separate sticker sdk?

### ISSUE THREAD

**Issue by khchoudhary8** [Giphy/giphy-android-sdk#159]
I know that giphy also has stickers in its giphy integration but i want to know if u have a separate sticker sdk or feature which is not in gif format something like the app Whatsapp. ? @ALexanderLonsky Sir

**Comment by ALexanderLonsky** [comment]
hey @khchoudhary8,
No, we don't. 
A Giphy Sticker is an animated GIF with a transparent background.
You can choose a file type to use: GIF or WEBP.
Please read more about stickers [here](https://engineering.giphy.com/new-stickers-api-available/).

I think there are some 3rd party tools to convert GIF to other formats, but I did not use them.
