### ISSUE TITLE
https://giphy.bintray.com/giphy-sdk - Bad Gateway - 502

### ISSUE THREAD

**Issue by SreehariRajeev** [Giphy/giphy-android-sdk#173]
The android SDK provided in your documentation (https://developers.giphy.com/docs/sdk#android) is down, bintray has been shutdown since May 2021, please provide a workaround for this issue.

**Comment by ALexanderLonsky** [comment]
@SreehariRajeev thank you for flagging this, we will update that one.

Please refer to [this](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#installation) documentation.

**Comment by Musacca** [comment]
Any update related to this issue?

**Comment by ALexanderLonsky** [comment]
@Musacca 
Giphy SDK has been fully migrated off of Jcenter by pointing the dependencies to [MavenCentral](https://search.maven.org/artifact/com.giphy.sdk/ui).
Please follow [the Installation](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#installation) guide.
