### ISSUE TITLE
How to add recents tab in giphy java?

### ISSUE THREAD

**Issue by sambhav2358** [Giphy/giphy-android-sdk#181]
I wanted to know that how can I get the recent gifs in giphy grid view.I was able to do it in `GiphyDialogFragment`. But I am unable to do it in `GiphyGridView`. Please help me and please provide the code in java. Thanks.

**Comment by ALexanderLonsky** [comment]
@sambhav2358 
Please refer to [this](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs_Java.md#recents) section.

Here is Java code to show Recents:
`binding.gifsGridView.setContent(GPHContent.Companion.getRecents());`

**Comment by sambhav2358** [comment]
Yes. I got that before itself. The thing is that I want to get recent gifs with searching. Is that possible?

**Comment by ALexanderLonsky** [comment]
The SDK does not provide this. 
`Recently Picked` are stored locally and the only info they have is their IDs.

**Comment by sambhav2358** [comment]
Thanks. It would be great if you add it. That would be better for users. For example if the user uses hundreds of Gifs and wants search among the recent ones, it will not be possible. Also for users with slow network will be frustrated as the gif will take a long time to load. Hope you understand.
