### ISSUE TITLE
Ability to segregate the sdk into module specific dependencies on a per feature basis such as sticker,gif etc

### ISSUE THREAD

**Issue by daljeet1337** [Giphy/giphy-android-sdk#187]
## Use case description
Since the size of the SDK is significant in comparison to modern day app bundle sizes, could we explore the possibility of segregating the SDK into smaller modules.

## Proposed solution
We could have gifs, stickers, clips etc as different modules so that if the use case of a user is to only use stickers and never use clips, they don't have to download the exoplayer dependency alongside and only have the sticker specific classes in place.

**Comment by ALexanderLonsky** [comment]
Thanks for noting this issue - we agree we should enable developers to adopt the features of the SDK with minimal dependencies. 
I'll pass this feedback onto my team & keep you in the loop.

**Comment by ALexanderLonsky** [comment]
@daljeet1337 We removed the ExoPlayer dependency as of version [2.2.0 ](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.2.0)

This is a breaking change, please follow the updated [clips documentation](https://github.com/Giphy/giphy-android-sdk/blob/main/clips.md#using-clips-in-sdk-v220-or-above).
