### ISSUE TITLE
Change Search Icon Color?

### ISSUE THREAD

**Issue by muaviyaijaz123** [Giphy/giphy-android-sdk#200]
## Describe your question in detail.
I want to change search icon color to white used in the finding gif search view. How can i achieve that?

Currently using following version:
implementation 'com.giphy.sdk:ui:2.3.4'

## Additional contexts
<img width="285" alt="Screenshot 2023-05-12 at 6 27 21 PM" src="https://github.com/Giphy/giphy-android-sdk/assets/90596703/dffb9d7f-9818-48aa-b159-f18afb9a5b49">

**Comment by ALexanderLonsky** [comment]
Hey @muaviyaijaz123,
Please refer to [this](https://github.com/Giphy/giphy-android-sdk/issues/199#issuecomment-1542487386) comment.

In that version, you can achieve it by:

```
GPHCustomTheme.apply {
            val currentNightMode = this@DemoActivity?.let {
                this@DemoActivity.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
            }
            val lightMode = (listOf(Configuration.UI_MODE_NIGHT_NO, Configuration.UI_MODE_NIGHT_UNDEFINED).contains(currentNightMode))
            defaultTextColor = Color.Black.hashCode()
            if (lightMode) {
                searchButtonIcon = ContextCompat.getDrawable(this@DemoActivity, com.giphy.sdk.ui.R.drawable.gph_ic_search_black)
            } else {
                searchButtonIcon = ContextCompat.getDrawable(this@DemoActivity, com.giphy.sdk.ui.R.drawable.gph_ic_search_white)
            }
        }
```

**Comment by ALexanderLonsky** [comment]
Update:

There is a new version available: 
`implementation "com.giphy.sdk:ui:2.3.5-rc4"`

Two new convenient functions are now available in the `GPHCustomTheme`.

`applyLightThemeProps() / applyDarkThemeProps()`

If you want to modify only certain color properties, you should use these functions:

```
GPHCustomTheme.apply {
            val currentNightMode = this@DemoActivity?.let {
                this@DemoActivity.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
            }
            val lightMode = (listOf(Configuration.UI_MODE_NIGHT_NO, Configuration.UI_MODE_NIGHT_UNDEFINED).contains(currentNightMode))
            defaultTextColor = Color.Black.hashCode()
            if (lightMode) {
                applyLightThemeProps()
                searchButtonIcon = ContextCompat.getDrawable(this@DemoActivity, com.giphy.sdk.ui.R.drawable.gph_ic_search_black)
            } else {
                applyDarkThemeProps()
                searchButtonIcon = ContextCompat.getDrawable(this@DemoActivity, com.giphy.sdk.ui.R.drawable.gph_ic_search_white)
            }
        }
```

**Comment by muaviyaijaz123** [comment]
Thanks for such detailed answer!

**Comment by ALexanderLonsky** [comment]
@muaviyaijaz123 Hey,

You can now switch to the [official version](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.3.5).

**Comment by muaviyaijaz123** [comment]
Sure, thanks for the update.
