### ISSUE TITLE
Get Giphy Attributes( size,height, width etc)?

### ISSUE THREAD

**Issue by muaviyaijaz123** [Giphy/giphy-android-sdk#201]
## Describe your question in detail.
Is there a way to get attributes of giphy like its size, height , width as it is needed in our project because we need to an object like this:

{
 {
 original={
        url=https: //[media4.giphy.com/media/t3sZxY5zS5B0z5zMIz/giphy.gif?cid=c4b036757q6x64xyacgd15qkmqzply9ws1ky70zy5icwcsw2&ep=v1_gifs_search&rid=giphy.gif&ct=g](http://media4.giphy.com/media/t3sZxY5zS5B0z5zMIz/giphy.gif?cid=c4b036757q6x64xyacgd15qkmqzply9ws1ky70zy5icwcsw2&ep=v1_gifs_search&rid=giphy.gif&ct=g),
        **width=500,
        height=281,
        size=11741706,**
        frames=167
    }
 }
}

**Comment by ALexanderLonsky** [comment]
Hey @muaviyaijaz123 ,
You can access all the media attributes through the `Image` model. 
To do so, you need to select the desired rendition:
`val image = media.imageWithRenditionType(RenditionType.original)`

then you can get the values:
```
image?.let {
    val width = it.width
    val height = it.height
    val size = it.gifSize // or it.webPSize
    val frames = it.frames
}

```
P.S. [Here](https://developers.giphy.com/docs/optional-settings/#rendition-guide) you can read more about the renditions.
