### ISSUE TITLE
error resource style/ShapeAppearanceOverlay.DifferentCornerSize not found.

### ISSUE THREAD

**Issue by VIkash2601** [Giphy/giphy-android-sdk#208]
## 🐛 Bug Report

I am unable to build the app after implementing the Giphy SDK and used it inside the fragment.

## To Reproduce

Modify below Dependencies;
1. implementation 'com.google.android.material:material:1.9.0'
2. implementation 'androidx.appcompat:appcompat:1.5.0'
3. implementation 'com.giphy.sdk:ui:2.3.8'

And then try to build the app.

(Write your steps here:)

1. Make above changes and build the project.

## Expected behavior

The app should build properly and on click of the button the Giphy Dialog should open.

## Actual Behavior

Build failed with below error;
**Android resource linking failed
error: resource style/ShapeAppearanceOverlay.DifferentCornerSize (aka com.app.spinnr.test:style/ShapeAppearanceOverlay.DifferentCornerSize) not found.**
![image](https://github.com/Giphy/giphy-android-sdk/assets/38423769/d7b63c05-f2d9-4247-935e-2fc0c19724cc)

## Your Environment

- Giphy Android SDK version: 2.3.8
- Device info (Emulator/Device? Android version? Debug/Release?):
1. Android Studio: Android Studio Giraffe | 2022.3.1
2. AGP: 
`plugins {
    id 'com.android.application' version '7.2.1' apply false
    id 'com.android.library' version '7.2.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.10' apply false
}`

**Comment by ALexanderLonsky** [comment]
@VIkash2601 Hey,
I've prepared a demo project where the Giphy dialog is invoked directly from the fragment. Replace `YOUR_API_KEY` with your actual key.
Please let me know if there's anything else I can help with.


[fragment_giphy_dialog.zip](https://github.com/Giphy/giphy-android-sdk/files/12311894/fragment_giphy_dialog.zip)

**Comment by VIkash2601** [comment]
Hi @ALexanderLonsky thank you for your reply. I will look into it. I have a case where I share the selected gif url to my server to save the chat history and get it in the API. And, currently I am able to render the gif as thumbnail in GPHMediaView but the gif does not play.

**Comment by ALexanderLonsky** [comment]
Have you successfully compiled your project and run the dialog? 
You might want to check out our [demo project](https://github.com/Giphy/giphy-android-sdk/tree/main), which allows you to interact with the SDK. In it, you can select media from the dialog and then display it in a list. In your situation, consider sending the GIF's ID instead of its URL, then use the [GPHCore.gifById(id)](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#media-ids) method. Additionally, [here's](https://github.com/Giphy/giphy-android-sdk/issues/158#issuecomment-942568067) a link to a similar issue that may help.

**Comment by VIkash2601** [comment]
One last question before I close this thread, is it possible to get the GIF using `media.<any url>`?

**Comment by ALexanderLonsky** [comment]
take a look at [this](https://github.com/Giphy/giphy-android-sdk/issues/191#issuecomment-1277562188)

**Comment by VIkash2601** [comment]
Sorry that I was unable to explain my question properly as the solution suggested by you is to fetch the URL that I am achieving properly for my Use Case. The concern is if I have the gifUrl from the server, is it possible to set this to GPHMediaView, get the GIF media data from it, and play the GIF.
