### ISSUE TITLE
[UX] Preview dialog is not closed with the back button in GiphyGridView

### ISSUE THREAD

**Issue by santi-petersen** [Giphy/giphy-android-sdk#210]
## 🐛 Bug Report

At least using GiphyGridView, if you long-click on a gif, a preview dialog is shown, but if you try to close it with back-button (the most intuitive way), the action is not handled and the activity finishes.

## To Reproduce

1. Long-click on a gif (using GiphyGridView)
1. Press back button

## Expected behavior

It should close the preview dialog.

Another possibility may be that we handle the back action and we close the dialog. 
We can enable an OnBackPressedCallback on didLongPressCell but we need a way to programmatically close the preview dialog and another event that needs to be called when the dialog is closed anyway (touching the screen, clicking "select", clicking the author or whatever) to again disable the OnBackPressedCallback

## Actual Behavior

It finishes the activity

## Your Environment

- Giphy Android SDK version: 2.3.9
- Device info (Emulator/Device? Android version? Debug/Release?): Samsung Galaxy S9+ -But I guess it happens on all devices-

**Comment by ALexanderLonsky** [comment]
Hey @santi-petersen,
Thanks for flagging this issue!
It has been resolved in the new version [2.3.10](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.3.10).

**Comment by santi-petersen** [comment]
> Hey @santi-petersen, Thanks for flagging this issue! It has been resolved in the new version [2.3.10](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.3.10).

Brilliant! 👌
