### ISSUE TITLE
Am Facing this

### ISSUE THREAD

**Issue by Arqais** [Giphy/giphy-android-sdk#217]
![Image] (https://github.com/Giphy/giphy-android-sdk/assets/66834904/bda06a2f-e6d0-4593-a6e0-bc6b3d8d9186)
How can i solve this as they mentioned my minsdk is 19 and still not working

**Comment by ALexanderLonsky** [comment]
hey @Arqais,
Try this version: [v2.3.13-fresco-v2.5.0](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.3.13-fresco-v2.5.0).
