### ISSUE TITLE
App name (Label) is displayed in the background for a split second while the `GiphyDialogFragment` is initialized

### ISSUE THREAD

**Issue by ygag-gopikrishnan** [Giphy/giphy-android-sdk#220]
## 🐛 Bug Report

App name is displayed in the background for a split second while the `GiphyDialogFragment` is initialized

## To Reproduce

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityGiphyContainerBinding.inflate(layoutInflater)
        window.decorView.setBackgroundColor(Color.TRANSPARENT)
        binding.container.setSystemUiVisibility(
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
                    View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
        )
        setContentView(binding.root)
        settings.mediaTypeConfig = arrayOf(GPHContentType.gif, GPHContentType.sticker, GPHContentType.text, GPHContentType.emoji)
        val dialog =
            GiphyDialogFragment.newInstance(settings.copy(selectedContentType = contentType))
        dialog.gifSelectionListener = getGifSelectionListener()
        dialog.show(supportFragmentManager, "gifs_dialog")
    }
```

https://github.com/Giphy/giphy-android-sdk/assets/124232293/bf742e59-687d-4cff-9f3c-fa451b397a90

## Expected behavior

- NA

## Actual Behavior

- The app name shouldn't be displayed in the background

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Giphy Android SDK version: `giphy-sdk-ui-version = "2.3.13"`
- Device info (Emulator/Device? Android version? Debug/Release?): Real device, Android 13 (Samsung galaxy note 20), 

## Reproducible Demo

- NA

**Comment by ygag-gopikrishnan** [comment]
Any updates on this?  @ALexanderLonsky @bassemali @asobrien @vmorarian

**Comment by ALexanderLonsky** [comment]
Hey @ygag-gopikrishnan,
I'm sorry for the late response. 
This issue does not seem to be that critical, I'll check it out later.

**Comment by ygag-gopikrishnan** [comment]
Fixed the issue with theming.
