### ISSUE TITLE
Crash on some devices.

### ISSUE THREAD

**Issue by buiduclam09** [Giphy/giphy-android-sdk#221]
## 🐛 Bug Report
File res/drawable/gph_sticker_bg_drawable_light.xml from drawable resource ID #0x7f0802fa
Caused by android.content.res.Resources$NotFoundException1. 
Android 10, Huawei

**Comment by ALexanderLonsky** [comment]
Hey @buiduclam09,
Which specific Huawei device are you experiencing problems with? 
You mentioned a drawable whose src attribute is pointed to a PNG file. We have these files available for the following drawable folders: drawable-hdpi, drawable-mdpi, drawable-xhdpi, drawable-xxhdpi, and drawable-xxxhdpi.
