### ISSUE TITLE
Apk size is increased from 32 MB to 39MB after integrating Giphy-sdk in android.

### ISSUE THREAD

**Issue by roopkishore101** [Giphy/giphy-android-sdk#223]
My current apk size was 32 which was using gradle version 7.4, but after integrating Giphy-sdk, I had to change my gradle version to 8.
and there were multiple changes in the entire project. 
but after creating the release build. I observed there is a 7 MB increase in apk size. 
can anyone explain the reason?

Thanks in advance.

**Comment by ALexanderLonsky** [comment]
Hey @roopkishore101,
you can analyze your APK using Android Studio by going to Build -> Analyze APK
