### ISSUE TITLE
How can we add my views in the Giphy Dialog?

### ISSUE THREAD

**Issue by roopkishore101** [Giphy/giphy-android-sdk#224]
I want to add TextView in the dialog at the top, and cross button at the top right corner.  and handle the clicks of that cross icon. How can I achieve this? 

Thanks

**Comment by ALexanderLonsky** [comment]
Hey @roopkishore101,
You can only customize the color scheme for the `GiphyDialogFragment`. To further extend customization, you should opt for the [grid-only](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#grid-only-and-giphygridview) solution, where you'll need to provide your own search field to obtain text input from the user, and update the grid's content in response to user interaction or searches.
For example, you can refer to [this](https://github.com/Giphy/giphy-android-sdk/blob/main/app/src/main/java/com/giphy/sdk/uidemo/GridViewDemoActivity.kt) demo.
