### ISSUE TITLE
GIFs not loading when connected to the WIFI

### ISSUE THREAD

**Issue by RakeshPatil111** [Giphy/giphy-android-sdk#225]
## 🐛 Bug Report

I am using Android SDK, when device is connected to the cellular network it works fine. But when device is connected to WIFI, GIF loading fails.

Step to reproduce
Integrate android SDK, and just launch application.

## Expected behavior
It should work fine irrespective network connected.

(Write what you thought would happen.)

## Actual Behavior
I get Failed to connect to api.giphy.com, ConnectionException.
## Your Environment
Android version 14
SDK 2.3.13

**Comment by ALexanderLonsky** [comment]
Hey @RakeshPatil111,
Are you sure that there are no firewalls or network security settings that might block the loading of GIFs when connected to the WiFi?

**Comment by RakeshPatil111** [comment]
There is no any setting or VPN, it may be the problem with some fixed WIFI networks/ISPs. My friends can see everything when the app is connected to WIFI(they have a diff network).

**Comment by ALexanderLonsky** [comment]
I'm sorry, but I can't assist you with this issue since we don't have any specific restrictions on loading GIFs.
