### ISSUE TITLE
Loading a gif overwrites rounded corners 

### ISSUE THREAD

**Issue by powerworr** [Giphy/giphy-android-sdk#43]
Loading a gif with 
```itemView.attachmentGifView.setMediaWithId(giphyMediaId)```
shows the rounded corners specified in the xml, but overwrites them with a rectangular image when it is loaded. Adding a cardView and clipping doesn't fix the issue.
``` 
<androidx.cardview.widget.CardView
   android:layout_width="wrap_content"
   android:layout_height="wrap_content"
   android:layout_gravity="end"
   app:cardCornerRadius="20dp"
   app:cardPreventCornerOverlap="false"
   app:cardUseCompatPadding="false" 
   app:elevation="0dp">

   <com.giphy.sdk.ui.views.GPHMediaView
       android:id="@+id/attachmentGifView"
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:maxWidth="200dp" />

</androidx.cardview.widget.CardView>
```

I didn't find a way to specify rounded corners in code or make them stay after specifying them in xml. Any help would be appreciated!

**Comment by powerworr** [comment]
I see you are extending facebook views and therefore some attributes for rounded corners are part of the `GPHMediaView`, but the are ignored. Do you provide a way to round them?

**Comment by rushabh1191** [comment]
@powerworr where you able to round the corners? I also have similar requirement.

**Comment by ALexanderLonsky** [comment]
@rushabh1191 please try [v2.0.7](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.7)
`GifView` has now `cornerRadius` property.
