### ISSUE TITLE
`cellPadding` not working for horizontal carousel

### ISSUE THREAD

**Issue by PiotrPrus** [Giphy/giphy-android-sdk#45]
Hi,
as I mentioned in this issue: https://github.com/Giphy/giphy-android-sdk-ui-example/issues/36, the cellPadding is not working. Right now the do value is correct, but padding is still not displayed for horizontal single row carousel. I have double check in the sample.
Steps to reproduce:
 - Run the sample app
 - Go to grid settings
 - set span count to 1
 - set padding to 10
The padding is missing

Expected behaviour: 
The cellPadding should work as it is for double row. 

Checked on following version:
1.2.6, 1.2.7, 1.2.8

**Comment by ALexanderLonsky** [comment]
horizontal carousel is deprecated
