### ISSUE TITLE
scrolling issue with com.giphy.sdk.ui.views.GiphyGridView

### ISSUE THREAD

**Issue by mihirmodiofficial** [Giphy/giphy-android-sdk#48]
scrolling not working 

<com.giphy.sdk.ui.views.GiphyGridView
    android:id="@+id/gifsGridView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:gphDirection="horizontal"
    app:gphSpanCount="2"
    app:gphCellPadding="12dp"
    app:gphShowCheckeredBackground="false"/>

**Comment by sambhav2358** [comment]
Change the orientation to `vertical`.
