### ISSUE TITLE
How to make fixed size cell in GiphyDialogFragment

### ISSUE THREAD

**Issue by mihirmodiofficial** [Giphy/giphy-android-sdk#50]
make all cells height width equal?

**Comment by ALexanderLonsky** [comment]
There is no possibility to do that for `GiphyDialogFragment`
Only `GiphyGridView` has `fixedSizeCells` option: [link](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#grid-only-and-giphygridview)
