### ISSUE TITLE
HTTP CLEARTEXT issue 

### ISSUE THREAD

**Issue by PandurangBangar** [Giphy/giphy-android-sdk#58]
Since I have implemented Giphy in app, my app api's does not working its gives below error. its working once I removed Giphy dependency from gradle in android. Giphy api's are working fine but my server api's getting cleartext issue because of Giphy. Please Help...... 

**Error:**
_HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to xyz.com not permitted by network security policy_

    **COMPILE_SDK_VERSION = 28
    BUILD_TOOL_VERSION = "28.0.3"

    MIN_SDK_VERSION = 23
    TARGET_SDK_VERSION = 28**

**my manifest application node**
 ```
<application
        android:usesCleartextTraffic="true"
        android:name=".RootApplication"
        android:allowBackup="false"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:roundIcon="@mipmap/ic_launcher"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
```

**Comment by bogdantmm92** [comment]
Hey @PandurangBangar, this seems a configuration issue on on the app side. Let us know if you pinpoint the exact issue and we can take it from there.
