### ISSUE TITLE
Bugs in loading videos on GiphyGridView

### ISSUE THREAD

**Issue by amitkle** [Giphy/giphy-android-sdk#73]
Hello,
I found two bugs using the GiphyGridView on "one+ 8 pro" device.
The GiphyGridView works great on other devices.
I've attached videos.
[giphy_videos.zip](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5008630/giphy_videos.zip)

**Comment by ALexanderLonsky** [comment]
hey @amitkle, thank you for filing the issue. We'll look into it.

**Comment by ALexanderLonsky** [comment]
@amitkle could you please try if [v2.0.1](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/2.0.1) fixes the issue?

**Comment by amitkle** [comment]
@ALexanderLonsky Hey, it seems like it fixed it :) 
Thank you very much!
